name: Node CI

on:
  push:
    branches:
      - master

jobs:
  build-on-ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: publish package
        run: |
          npm ci
          npm run build --if-present
          npm test
          npm publish:npm
        env:
          CI: true
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

